import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.center}>
          <h1>
            タイトル
          </h1>
          <h2>
            ゲーム名
          </h2>
          <p>
            テストテストテストテストテストテストテストテストテストテスト
          </p>
          <h2>
            ゲーム名
          </h2>
          <h2>
            ゲーム名
          </h2>
          <h2>
            ゲーム名
          </h2>
        </div>
      </main>
    </>
  )
}
